// Generated by CoffeeScript 1.6.2
var BadgeController;

BadgeController = (function() {
  function BadgeController(store, classesService) {
    var _this = this;

    this.store = store;
    this.classesService = classesService;
    chrome.browserAction.onClicked.addListener(function(tab) {
      var tabId;

      tabId = tab.id;
      return chrome.tabs.executeScript(tabId, {
        file: "assets/vendors/jquery.min.js"
      }, function() {
        return chrome.tabs.executeScript(tabId, {
          file: "lib/controller/commands/links.js"
        }, function() {
          return chrome.tabs.sendRequest(tabId, {}, function(items) {
            _this.store.addIncomingTasks(items);
            return chrome.tabs.create({
              url: "options.html"
            });
          });
        });
      });
    });
  }

  return BadgeController;

})();
