// Generated by CoffeeScript 1.6.2
var Alert;

Alert = (function() {
  function Alert() {
    this.name = '.alerts';
    this.index = 0;
    this.visible = 0;
  }

  return Alert;

})();

angular.module('Alert', []).factory('alert', function($window) {
  return new Alert;
});
