// Generated by CoffeeScript 1.6.2
var getCourse, getLectures, getSections, getVideo, trim;

trim = function(str) {
  str = str.replace(/^\s+/g, '');
  return str.replace(/\s+$/g, '');
};

getVideo = function(link) {
  return $(link).attr('data-modal-iframe');
};

getLectures = function(section) {
  return $(section).next().find('li').map(function() {
    var link;

    link = $(this).find('.lecture-link');
    return {
      title: trim($(link).text()),
      video: getVideo(link)
    };
  }).get();
};

getSections = function() {
  return $('.course-item-list-header').map(function() {
    return {
      title: trim($(this).find('h3').text()),
      lectures: getLectures(this)
    };
  }).get();
};

getCourse = function() {
  var name;

  name = $('.course-topbanner-name').text();
  return {
    course: trim(name),
    sections: getSections()
  };
};

chrome.extension.onRequest.addListener(function(request, sender, sendResponse) {
  return sendResponse(getCourse());
});
