// Generated by CoffeeScript 1.6.2
var Plan;

Plan = (function() {
  function Plan(data) {
    this.enabled = $(data).attr('enabled');
    this.shortKey = $(data).attr('shortKey');
    this.shortName = $(data).attr('shortName');
    this.name = $(data).attr('name');
    this.key = $(data).attr('key');
    this.projectName = '';
  }

  Plan.prototype.projectKey = function() {
    return this.key.split("-")[0];
  };

  return Plan;

})();
